### ISSUE TITLE
the program crashes if file has 0 byte length

### ISSUE THREAD

**Issue by XaTTa6bl4** [whoozle/android-file-transfer-linux#179]
Log from cli:
```
uploadFile  "IMG_20150717_181307.jpg"  as  "IMG_20150717_181307.jpg" 
sending  0  bytes 
new object id:  8290 , sending... 
Floating point exception
(исключение в операции с плавающей точкой)
```

**Comment by whoozle** [comment]
fixed in 41f49de2ee70e776c276295f31e3d11d71193e53

**Comment by whoozle** [comment]
please check if it worked for you

**Comment by XaTTa6bl4** [comment]
Hi, thanks, but the problem is still here:

`directories[0]:  "~/backup/Telegram/Telegram Audio"  ->  4294967295 
uploadFile  ".nomedia"  as  ".nomedia" 
sending  0  bytes 
new object id:  14080 , sending... 
Исключение в операции с плавающей точкой`

**Comment by whoozle** [comment]
could you please pull and check again. Should be fixed in 156f0358611f73bcc14fb89537937c45b385a867. 
Basically I guarded all divisions in the project lol

**Comment by whoozle** [comment]
I didnt realise it was qt you're using

**Comment by whoozle** [comment]
could you please check that the problem was fixed? :)

**Comment by grim7reaper** [comment]
Hi,

I also had this problem and when compiling from master the crash is no longer here so I would say that the problem is fixed.

Thanks for the fix!

**Comment by XaTTa6bl4** [comment]
@whoozle sorry, I missed that you answered here:(
I'll check it out I think on May 3rd, when I get to my PC

**Comment by XaTTa6bl4** [comment]
@whoozle I've just tested. There is no crash now, but now zero-byte files doesn't really copy. It skipped with error 0x2002:
`
data:  QDropData(0x108f290) 1 -1 -1 
files dropped:  ("/tmp/nomedia") 
uploadFiles  ("/tmp/nomedia") 
uploading 0 bytes 
uploading file  "/tmp/nomedia" , parent:  "/tmp" 
adding first parent path 
directories[0]:  "/tmp"  ->  4294967295 
uploadFile  "nomedia"  as  "nomedia" 
sending  0  bytes 
new object id:  30441 , sending... 
uploading file  "/tmp/nomedia"  failed:  "Get: invalid response code GeneralError (0x2002)" 
finishing queue 
finished 
`

**Comment by whoozle** [comment]
Could you test on the latest master please?

**Comment by XaTTa6bl4** [comment]
Hi! Yes, I'll try and make a feedback

**Comment by XaTTa6bl4** [comment]
Hi. I've just tested, for now any files can be copied, when copying a directory or separately, without errors. Thank you!
